rails/social_site/config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get 'show_admin'=>  'users#show_admin'
  get 'privacy'   =>  'static_pages#privacy'
  get 'feed'      =>  'static_pages#feed'
  get 'featured'  =>  'static_pages#feature'
  get 'resource'  =>  'static_pages#resource_material'
  get 'signup'    =>  'users#new'
  get 'login'     =>  'sessions#new'
  post 'login'    =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'
  get '/subscribe'              => 'static_pages#subscribe'
  get '/unsubscribe'            => 'static_pages#unsubscribe'
  get '/unsubscribe_notify'     => 'static_pages#unsubscribe_notify'
  post '/send_email',           to: 'static_pages#send_email', as: 'send_email'
  get 'auth/facebook/callback'  => 'sessions#create_facebook'
  get 'auth/instagram/callback' => 'sessions#create_instagram'
  get 'auth/twitter/callback'   => 'sessions#create_facebook'
  get 'auth/failure'            => 'users#new'
  post 'notification'           => 'simple_mail#notification'
  post 'complaint'              => 'simple_mail#complaint'
  get '/sitemap.xml.gz', to: redirect("https://s3-us-west-2.amazonaws.com/hyouka/sitemaps/sitemap.xml.gz"), as: :sitemap
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_reset, only: [:new, :create, :edit, :update]
  resources :microposts do
    resources :comments,     only: [:create, :destroy]
    get 'toggle_approve',    :on => :member
    member do
      get 'like'
      get 'unlike'
    end
  end
  get 'microposts/:id/*slug'    => 'microposts#show'
  resources :ads,            only: [:show, :create, :edit, :update]
  resources :relationships,  only: [:create, :destroy]
  resources :notifications,  only: [:index, :destroy]
  
end

rails/social_site/app/views/layouts/_footer.html.erb
<% if logged_in? %>
  <footer class="footer nav navbar-fixed-bottom">
      <%= link_to "", feed_path + "#scrollupmicropost", taget:'_self', class: "glyphicon glyphicon-plus btn-circle"  %>
  </footer>
<% end %>

rails/social_site/app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Oraciones", feed_path, class: "navbar-brand", id:"logo"%>
    </div>

    <div class="collapse navbar-collapse nav navbar-nav navbar-right" id="bs-example-navbar-collapse-1">
          <li><%= link_to "Usuarios", users_path, class: "navigation-text" %></li>
        <% if logged_in? %>
          <li><%= link_to "Mis Amigos", featured_path, class: "navigation-text" %></li>
          <li><%= link_to  "(#{current_user.notifications.count}) Notificaciones", notifications_path, class: "navigation-text" %></li>
          <li><%= link_to gravatar_for(current_user, size: '30', css: "img-circle") + ' Mi Perfil' , current_user, style: "padding-top:12px; padding-bottom:8px;", class: "navigation-text" %></li>
          <li><%= link_to "", logout_path, class: "navigation-text glyphicon glyphicon-off delete", method: "delete" %></li>
        <% else %>
          <li><%= link_to_unless logged_in?, "Iniciar Session", login_path, class: "navigation-text" %></li>
        <% end %>
    </div>
  </div>
</nav>

rails/social_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oraciones</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta property="og:url"           content="<%= request.url %>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Presiona aqui para escribir tu oracion" />
  <meta property="og:description"   content="<%= yield_meta_tag(:description, 'Un lugar para juntarnos a orar en el nombre de Dios.') %>" />
  <meta property="og:image"         content="<%= yield_meta_tag(:image, 'https://s3-us-west-2.amazonaws.com/hyouka/static_files/prayer.jpg') %>" />
  <meta property="fb:app_id"        content="721817757980628">

  <!-- <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@oremos_a_dios">
  <meta name="twitter:creator" content="@oremos_a_dios">
  <meta name="twitter:title" content="Pido Oracion ...">
  <meta name="twitter:description" content="Un lugar para juntarnos a orar en el nombre de Dios.">
  <meta name="twitter:image" content="<%= yield_meta_tag(:image, 'https://s3-us-west-2.amazonaws.com/hyouka/static_files/prayer.jpg') %>"> -->
</head>
<body>
  <!-- <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));
  </script> -->
  <%= render 'layouts/header' %>
  <div class="container body">
    <div class="alert alert-info">
      <a href="/resource">Presiona aqui: Para acceder a guias cristianas Gratis</a>
      <button class="close" data-dismiss="alert">
        ×
      </button>
    </div>
    <% flash.each do |message_type, message| %>
    <% message_type = 'info' if message_type == "notice" %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
      <button class="close" data-dismiss="alert">
        ×
      </button>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-88914426-1', 'auto');
    ga('send', 'pageview');
  </script>
  <script>
    function loadImage(){
      $.each($('.load-image'), function(index, obj){
        console.log("Getting the image");
        var img = new Image();
        img.src = $(obj).attr('data-source');

        $(img).ready(function(){
          console.log("Inserting the image");
          $(obj).attr('src', img.src);
        })
      })
    };
    loadImage();
  </script>
</body>
</html>